language: python
python:
  - "2.7"
env:
  global:
  - TRAVIS_BUILD=true
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - ./manage.py test tests
  - coverage run --omit='*virtualenv*' manage.py test --noinput
after_success: coveralls
