# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.FileField(upload_to=editor.models.get_photo_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='public_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='effects',
        ),
        migrations.DeleteModel(
            name='SocialProfile',
        ),
        migrations.AddField(
            model_name='effect',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Photo'),
        ),
    ]
