# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20160306_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date_edited',
            new_name='date_modified',
        ),
    ]
