# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='effect',
            field=models.ImageField(max_length=255, upload_to=editor.models.get_photo_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default=editor.models.generate_uid, max_length=255),
        ),
    ]
