# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20160321_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_effect',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
