# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_photo_image_effect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_effect',
            field=models.ImageField(blank=True, max_length=255, upload_to=editor.models.get_effect_path),
        ),
        migrations.DeleteModel(
            name='Effect',
        ),
    ]
